name: First DevOps Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print a Message
        run: echo "Hello DevOps World 🚀"

      - name: Print Repository Name
        run: echo "Repository is ${{ github.repository }}"
